# makefile 
help: # list make build options
	@echo Use make with any of these options:
	@grep "^[a-zA-Z]*:" makefile | sed "s/^/    /"
	@echo
	@echo You may like to run
	@echo "	" make config
	@echo to check you have the software you need
	@echo
	@echo basic use is:
	@echo "  	" make pdf
	@echo ... which makes clean PDF documents
	@echo Then say make tidyup to delete easily rebuilt files
	@echo
		
config: # check you have the right configurations to run the systems
	@echo Check you have a suitable configuration ...
	@echo
	@echo Data was processed using node v12.13.0
	@echo You have:; node -v | sed "s/^/    /"
	@echo;echo "Latex was processed using XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)"
	@echo You have:; xelatex -v | sed "s/^/    /"
	@echo;echo "Bibtex was processed using BibTeX 0.99d (TeX Live 2021)"
	@echo You have:; bibtex -v | sed "s/^/    /"
	@echo;echo "Git was processed using git version 2.32.0 (Apple Git-132)"
	@echo You have:; git --version | sed "s/^/    /"
	
data: # generate the Latex data files from data.js and downloaded Git repositories
	@echo generate all files and analyses from JSON data in data.js
	-node data.js
	@echo
	@echo generate all data from the published models cited in the paper
	@echo Note that we will be generating data from the papers repositories, and these may have been updated by their authors
	cd models; run
	
tidyup: # remove all easily generated files except the main PDFs
	@echo Remove all files that can be regenerated by running run, except main PDFs
	rm -f paper-seb-*.aux generated-* paper-seb-*.bbl paper-seb-*.blg summarise.aux data-check.html 
	rm -f flagData.nb
	rm -rf *.log *.out *.dvi
	@echo This has left these generated PDFs you can either keep or delete manually
	-@ls paper*.pdf
	@echo The following data files have been left untouched - create them with make data, or remove them by using make reallytidyup
	@echo "	" flagData.nb - Flags expressed as Mathematica code
	@echo "	" allData.csv - All data expressed in CSV
	@echo "	" generated-assessments.tex - Main summary table for Supplementary Material
	@echo "	" generated-supplementary-references.tex - Reference list for Supplementary Material
	@echo "	" generated-summary-table.tex - Short summary table
	@echo "	" generated-constants.tex - Generated common definitions and constants
	@echo "	" generated-legend.tex - Legend for the main assessment table
	@echo "	" generated-data-check.html - Convenient list of data sources with DOIs in HTML
	@echo If any are missing, rerun node data.js - or run make clean 
 
reallytidyup: # better than tidyup - remove ALL files that can be recreated
	@echo Remove ALL files that can be recreated, including PDFs and files made by processing the JSON data
	make tidyup
	rm -f paper-seb-*.pdf
	# remove other files made by running node data.js
	rm -f flagData.nb allData.csv data-check.html
	# this was created if we did a make one-file -- the original name of the PDF, ftpeed to http://www.harold.thimbleby.net/reliable-models.pdf
	rm -f reliable-models.pdf
	# finally, remove all the recoverable stuff in the models directory
	cd models; tidyup
	rm -f allGitRepos.sh
	rm -f summarise.pdf
	rm -f allGitRepoCitations.tex
	rm -f expanded*
		
pdf: # make PDF files paper-seb-main.pdf and paper-seb-supplementary-material.pdf
	make data
    # LOTS of latex runs to make sure the .aux files are all correctly synced
    # eg inserting the table of contents changes page numbering, so it needs formatting again, etc
	xelatex paper-seb-supplementary-material.tex
	bibtex paper-seb-supplementary-material
	echo Do not worry bibtex cannot find database entries for "ref-16" etc as they are in another file
	xelatex paper-seb-supplementary-material.tex
	xelatex paper-seb-supplementary-material.tex
	xelatex paper-seb-main.tex
	bibtex paper-seb-main
	xelatex paper-seb-main.tex
	xelatex paper-seb-supplementary-material.tex
	xelatex paper-seb-supplementary-material.tex
	xelatex paper-seb-main.tex
	xelatex paper-seb-supplementary-material.tex
	@echo Unfortunately, paper-seb-main.tex has items in its bibiography that cross-refer to more bibliography items, so we need another run of bibtex etc
	bibtex paper-seb-main
	xelatex paper-seb-main.tex
	@echo and then the references in paper-seb-supplementary-material.tex are renumbered to follow on paper-seb-main.tex
	xelatex paper-seb-supplementary-material.tex
	@echo and paper-seb-main.tex refers to those numbers... so it needs updating again
	xelatex paper-seb-main.tex
	@echo "----------------------------------------------------------------"
	@echo You have now got these PDFs:
	@ls -C *paper*pdf
	@echo "-- That should say (at least):" paper-seb-main.pdf paper-seb-supplementary-material.pdf
	@echo
	@echo Plus some .aux/.out/.blg/etc files you can delete by running make tidyup
	@echo "----------------------------------------------------------------"
	
zip: # make a zip archive of everything in the directory
	@echo This zips everything in the current directory. Use make archive to delete junk before zipping
	# to make sure zip file has no junk in it, just remove it
	rm -f everything.zip
	zip everything *
	
archive: # remove recoverable files in the directory then make the Latex and CSV etc data files for uploading to an archive
	make reallytidyup
	make data
	rm -f generated-*
	rm -f everything.zip
	make zip
	echo Now upload *.zip
	
# for my private use
# This creates (and preserves) a single PDF, reliable-models.pdf, maintained at http://www.harold.thimbleby.net
singlefile: # make a single PDF file reliable-models.pdf (paper + appendix) all in one
	make one-file

one-file: paper-seb-main.pdf paper-seb-supplementary-material.pdf # concatenate files for my FTP site
	pdfunite paper-seb-main.pdf paper-seb-supplementary-material.pdf reliable-models.pdf

zipData: # just make a zip archive of the data (as required for Dryad repository)
	make data
	@echo NB You will get some undefined reference warnings, as the data is not typeset in the papers which it cross-references
	rm -f dryad-data.zip
	zip dryad-data README.md data.js

plos: # expand all LaTeX files (to flatten \input etc) for PLOS, then make PDFs
	node expand.js
	xelatex expanded-paper-seb-supplementary-material.tex
	xelatex expanded-paper-seb-supplementary-material.tex
	xelatex expanded-paper-seb-supplementary-material.tex
	xelatex expanded-paper-seb-main.tex
	xelatex expanded-paper-seb-main.tex
	pdfunite expanded-paper-seb-main.pdf expanded-paper-seb-supplementary-material.pdf reliable-models.pdf
	echo you now have expanded*pdf as well as the expanded source files expanded*tex and reliable-models.pdf which combines them as a single file
    